
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './database.types';

const SUPABASE_URL = "https://kcsgaqbmguazebsbwkiz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtjc2dhcWJtZ3VhemVic2J3a2l6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NDk5OTgsImV4cCI6MjA1OTMyNTk5OH0.34FvdU9h5RLZCjEx0cmivZnJy0948b5Yrj-vujXHh5s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
